# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lesson1212' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
'SnapKit'
  # Pods for Lesson1212

  target 'Lesson1212Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lesson1212UITests' do
    # Pods for testing
  end

end
